// ignore_for_file: avoid_print
import 'dart:io';

/// Generates `l10n_forwarders.g.dart` — a `class L10n` of static accessors
/// mirroring every getter and method on the generated `AppLocalizations`.
///
/// Why: interceptors, notifiers, and services have no `BuildContext`, so
/// `AppLocalizations.of(context)` is unavailable there. `L10n.sessionExpired`
/// works anywhere once `L10n.init(context)` has run.
///
/// Run via `dart run tool/update_l10n.dart`, which calls `flutter gen-l10n`
/// first. Running this alone against stale generated output produces stale
/// forwarders.
void main() {
  const dir = 'lib/core/localization/l10n';
  final source = File('$dir/app_localizations.dart');
  if (!source.existsSync()) {
    stderr.writeln('Missing ${source.path}. Run `flutter gen-l10n` first.');
    exit(65);
  }

  final body = _abstractClassBody(source.readAsStringSync());
  if (body == null) {
    stderr.writeln('Could not find `abstract class AppLocalizations` body.');
    exit(65);
  }

  final getters = RegExp(
    r'^\s*String\s+get\s+(\w+);',
    multiLine: true,
  ).allMatches(body).map((m) => m.group(1)!).toList();

  final methods = RegExp(r'^\s*String\s+(\w+)\(([^)]*)\);', multiLine: true)
      .allMatches(body)
      .map((m) => (name: m.group(1)!, params: m.group(2)!))
      .toList();

  final buffer = StringBuffer()
    ..writeln(
      '// GENERATED BY tool/generate_l10n_forwarders.dart — DO NOT EDIT.',
    )
    ..writeln('// Regenerate with: dart run tool/update_l10n.dart')
    ..writeln()
    ..writeln('part of \'../localization.dart\';')
    ..writeln()
    ..writeln('/// Context-free access to generated localized strings.')
    ..writeln('abstract final class L10n {')
    ..writeln('  static AppLocalizations? _current;')
    ..writeln('  static Locale? _currentLocale;')
    ..writeln()
    ..writeln('  /// Caches the active [AppLocalizations]. Call from a widget')
    ..writeln('  /// high in the tree — [L10nListener] does this for you.')
    ..writeln('  static void init(BuildContext context) {')
    ..writeln('    _current = AppLocalizations.of(context);')
    ..writeln('    _currentLocale = Localizations.localeOf(context);')
    ..writeln('  }')
    ..writeln()
    ..writeln('  static String get currentLanguageCode =>')
    ..writeln('      _currentLocale?.languageCode ?? \'en\';')
    ..writeln('  static bool get isArabic => currentLanguageCode == \'ar\';')
    ..writeln('  static bool get isEnglish => currentLanguageCode == \'en\';')
    ..writeln()
    ..writeln('  static AppLocalizations get _tr {')
    ..writeln('    final value = _current;')
    ..writeln('    if (value == null) {')
    ..writeln('      throw StateError(')
    ..writeln('        \'L10n used before init(). Ensure L10nListener is \'')
    ..writeln('        \'mounted above the widget that reads it.\',')
    ..writeln('      );')
    ..writeln('    }')
    ..writeln('    return value;')
    ..writeln('  }')
    ..writeln();

  for (final name in getters) {
    buffer.writeln('  static String get $name => _tr.$name;');
  }
  for (final method in methods) {
    final args = _argumentNames(method.params);
    buffer.writeln(
      '  static String ${method.name}(${method.params}) => '
      '_tr.${method.name}($args);',
    );
  }

  buffer.writeln('}');

  File('$dir/l10n_forwarders.g.dart').writeAsStringSync(buffer.toString());
  print(
    'Generated $dir/l10n_forwarders.g.dart '
    '(${getters.length} getters, ${methods.length} methods)',
  );
}

/// Extracts the body of `abstract class AppLocalizations { ... }` by counting
/// braces, so nested bodies do not terminate the match early.
String? _abstractClassBody(String source) {
  final start = source.indexOf('abstract class AppLocalizations');
  if (start == -1) return null;
  final open = source.indexOf('{', start);
  if (open == -1) return null;

  var depth = 0;
  for (var i = open; i < source.length; i++) {
    if (source[i] == '{') depth++;
    if (source[i] == '}') {
      depth--;
      if (depth == 0) return source.substring(open + 1, i);
    }
  }
  return null;
}

/// Turns a parameter list such as `Object count, String name` or
/// `{required int count}` into a call-site argument list.
String _argumentNames(String params) {
  if (params.trim().isEmpty) return '';
  final named = params.trim().startsWith('{');
  final cleaned = params.replaceAll(RegExp(r'[{}]'), '');

  return cleaned
      .split(',')
      .map((part) => part.trim())
      .where((part) => part.isNotEmpty)
      .map((part) {
        final name = part.split(RegExp(r'\s+')).last;
        return named ? '$name: $name' : name;
      })
      .join(', ');
}
