// ignore_for_file: avoid_print
import 'dart:io';

/// Generates `l10n_forwarders.g.dart` — a `class L10n` of static accessors
/// mirroring every getter and method on the generated `AppLocalizations`.
///
/// Why: interceptors, notifiers, and services have no `BuildContext`, so
/// `AppLocalizations.of(context)` is unavailable there. `L10n.sessionExpired`
/// works anywhere once `L10n.init(context)` has run.
///
/// Run via `dart run tool/update_l10n.dart`, which calls `flutter gen-l10n`
/// first. Running this alone against stale generated output produces stale
/// forwarders.
void main() {
  const dir = 'lib/core/localization/l10n';
  final source = File('$dir/app_localizations.dart');
  if (!source.existsSync()) {
    stderr.writeln('Missing ${source.path}. Run `flutter gen-l10n` first.');
    exit(65);
  }

  final body = _abstractClassBody(source.readAsStringSync());
  if (body == null) {
    stderr.writeln('Could not find `abstract class AppLocalizations` body.');
    exit(65);
  }

  final getters = RegExp(
    r'^\s*String\s+get\s+(\w+);',
    multiLine: true,
  ).allMatches(body).map((m) => m.group(1)!).toList();

  final methods = RegExp(r'^\s*String\s+(\w+)\(([^)]*)\);', multiLine: true)
      .allMatches(body)
      .map((m) => (name: m.group(1)!, params: m.group(2)!))
      .toList();

  // A generated `AppLocalizations` always declares at least one getter
  // (`appTitle` or similar). Zero means the brace/regex parse above failed —
  // most likely an ARB `@key.description` containing a stray `}` — not that
  // the ARB is genuinely empty. Never let that silently ship an empty class.
  if (getters.isEmpty && methods.isEmpty) {
    stderr.writeln(
      'Parsed zero getters/methods out of `abstract class AppLocalizations`. '
      'That should never happen for a real ARB, so treating this as a '
      'parser failure rather than overwriting $dir/l10n_forwarders.g.dart '
      'with an empty class.',
    );
    exit(65);
  }

  final buffer = StringBuffer()
    ..writeln(
      '// GENERATED BY tool/generate_l10n_forwarders.dart — DO NOT EDIT.',
    )
    ..writeln('// Regenerate with: dart run tool/update_l10n.dart')
    ..writeln()
    ..writeln('part of \'../localization.dart\';')
    ..writeln()
    ..writeln('/// Context-free access to generated localized strings.')
    ..writeln('abstract final class L10n {')
    ..writeln('  static AppLocalizations? _current;')
    ..writeln('  static Locale? _currentLocale;')
    ..writeln()
    ..writeln('  /// Caches the active [AppLocalizations]. Call from a widget')
    ..writeln('  /// high in the tree, e.g. from the builder callback in')
    ..writeln('  /// lib/app.dart.')
    ..writeln('  static void init(BuildContext context) {')
    ..writeln('    _current = AppLocalizations.of(context);')
    ..writeln('    _currentLocale = Localizations.localeOf(context);')
    ..writeln('  }')
    ..writeln()
    ..writeln(
      '  static String get currentLanguageCode => _locale.languageCode;',
    )
    ..writeln('  static bool get isArabic => currentLanguageCode == \'ar\';')
    ..writeln('  static bool get isEnglish => currentLanguageCode == \'en\';')
    ..writeln()
    ..writeln('  static Never _notInitialized() {')
    ..writeln('    throw StateError(')
    ..writeln(
      '      \'L10n used before init(). Call L10n.init(context) high \'',
    )
    ..writeln(
      '      \'in the widget tree, e.g. from the builder callback in \'',
    )
    ..writeln('      \'lib/app.dart.\',')
    ..writeln('    );')
    ..writeln('  }')
    ..writeln()
    ..writeln(
      '  static Locale get _locale => _currentLocale ?? _notInitialized();',
    )
    ..writeln()
    ..writeln(
      '  static AppLocalizations get _tr => _current ?? _notInitialized();',
    )
    ..writeln();

  for (final name in getters) {
    buffer.writeln('  static String get $name => _tr.$name;');
  }
  for (final method in methods) {
    final args = _argumentNames(method.params);
    buffer.writeln(
      '  static String ${method.name}(${method.params}) => '
      '_tr.${method.name}($args);',
    );
  }

  buffer.writeln('}');

  final output = File('$dir/l10n_forwarders.g.dart');
  output.writeAsStringSync(buffer.toString());

  // `dart format` always rewraps this boilerplate (some lines run past the
  // 80-column default), so format here rather than leaving every pipeline
  // run to dirty the tree and fail the `dart format --set-exit-if-changed`
  // CI gate.
  final format = Process.runSync('dart', ['format', output.path]);
  stdout.write(format.stdout);
  stderr.write(format.stderr);
  if (format.exitCode != 0) {
    stderr.writeln('dart format failed on ${output.path}.');
    exit(format.exitCode);
  }

  print(
    'Generated $dir/l10n_forwarders.g.dart '
    '(${getters.length} getters, ${methods.length} methods)',
  );
}

/// Extracts the body of `abstract class AppLocalizations { ... }` by
/// stripping comments (so a `///` doc comment carrying an ARB
/// `@key.description` with a stray `}` cannot corrupt the brace count) and
/// then counting braces, so nested bodies do not terminate the match early.
String? _abstractClassBody(String source) {
  final stripped = _stripComments(source);
  final start = stripped.indexOf('abstract class AppLocalizations');
  if (start == -1) return null;
  final open = stripped.indexOf('{', start);
  if (open == -1) return null;

  var depth = 0;
  for (var i = open; i < stripped.length; i++) {
    if (stripped[i] == '{') depth++;
    if (stripped[i] == '}') {
      depth--;
      if (depth == 0) return stripped.substring(open + 1, i);
    }
  }
  return null;
}

/// Removes `//` line comments and `/* */` block comments from Dart source,
/// leaving string literals untouched so a comment containing quote-like
/// punctuation can't desync the scan, and so a real string containing `//`
/// (a URL, say) is never mistaken for a comment.
String _stripComments(String source) {
  final buffer = StringBuffer();
  final length = source.length;
  var i = 0;

  while (i < length) {
    final char = source[i];
    final next = i + 1 < length ? source[i + 1] : '';

    if (char == '/' && next == '/') {
      final end = source.indexOf('\n', i);
      i = end == -1 ? length : end;
      continue;
    }

    if (char == '/' && next == '*') {
      final end = source.indexOf('*/', i + 2);
      i = end == -1 ? length : end + 2;
      continue;
    }

    if (char == '\'' || char == '"') {
      final quote = char;
      buffer.write(char);
      i++;
      while (i < length) {
        final c = source[i];
        buffer.write(c);
        if (c == r'\' && i + 1 < length) {
          buffer.write(source[i + 1]);
          i += 2;
          continue;
        }
        i++;
        if (c == quote) break;
      }
      continue;
    }

    buffer.write(char);
    i++;
  }

  return buffer.toString();
}

/// Turns a parameter list such as `Object count, String name` or
/// `{required int count}` into a call-site argument list.
String _argumentNames(String params) {
  if (params.trim().isEmpty) return '';
  final named = params.trim().startsWith('{');
  final cleaned = params.replaceAll(RegExp(r'[{}]'), '');

  return cleaned
      .split(',')
      .map((part) => part.trim())
      .where((part) => part.isNotEmpty)
      .map((part) {
        final name = part.split(RegExp(r'\s+')).last;
        return named ? '$name: $name' : name;
      })
      .join(', ');
}
