// GENERATED BY tool/generate_l10n_forwarders.dart — DO NOT EDIT.
// Regenerate with: dart run tool/update_l10n.dart

part of '../localization.dart';

/// Context-free access to generated localized strings.
abstract final class L10n {
  static AppLocalizations? _current;
  static Locale? _currentLocale;

  /// Caches the active [AppLocalizations]. Call from a widget
  /// high in the tree, e.g. from the builder callback in
  /// lib/app.dart.
  static void init(BuildContext context) {
    _current = AppLocalizations.of(context);
    _currentLocale = Localizations.localeOf(context);
  }

  static String get currentLanguageCode => _locale.languageCode;
  static bool get isArabic => currentLanguageCode == 'ar';
  static bool get isEnglish => currentLanguageCode == 'en';

  static Never _notInitialized() {
    throw StateError(
      'L10n used before init(). Call L10n.init(context) high '
      'in the widget tree, e.g. from the builder callback in '
      'lib/app.dart.',
    );
  }

  static Locale get _locale => _currentLocale ?? _notInitialized();

  static AppLocalizations get _tr => _current ?? _notInitialized();

  static String get appTitle => _tr.appTitle;
  static String get signIn => _tr.signIn;
  static String get signOut => _tr.signOut;
  static String get email => _tr.email;
  static String get password => _tr.password;
  static String get home => _tr.home;
  static String get settings => _tr.settings;
  static String get language => _tr.language;
  static String get themeMode => _tr.themeMode;
  static String get retry => _tr.retry;
  static String get fieldRequired => _tr.fieldRequired;
  static String get errorGeneric => _tr.errorGeneric;
  static String get sessionExpired => _tr.sessionExpired;
}
